# This is sample config file.
# Please customize me

meta:
  browser: chrome

organizations:
  - name: sumomo
    short: sumo
  - name: komomo
    short: komo

grid:
  sumomo:
    github:
      value: true # URL | true | string
      description: 'My sumomo GitHub'
    slack: sumomo-inc # URL | true | string
    gmail: https://example.com/ # URL | number
    google-calendar: 1 # URL | number
    aws: sumomo
    gcp: 0 # URL | number
    backlog: true # URL | true | string
    _customs:
      - name: jobcan
        short: jc
        url: https://example.com/jobcan
      - name: foo
        url: https://example.com/sumomo/foo
  komomo:
    github: true
    slack: true
